const FOLLOW = 'FOLLOW';
const UNFOLLOW = 'UNFOLLOW';
const ADD_POST = 'ADD-POST';
const SET_USERS = 'SET_USERS';
const SET_STATUS = 'SET_STATUS';
const DELETE_POST = 'SET_STATUS';
const SEND_MESSAGE = 'SEND-MESSAGE';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_INITIALIZED = 'SET_INITIALIZED';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_USER_PROFILE = 'SET_USER_PROFILE';
const SAVE_PHOTO_SUCCESS = 'SAVE_PHOTO_SUCCESS';
const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
const SET_CAPTCHA_URL_SUCCESS = 'SET_CAPTCHA_URL_SUCCESS';
const UPDATE_NEW_MESSAGE_BODY = 'UPDATE-NEW-MESSAGE-BODY';
const TOGGLE_FOLLOWING_PROGRESS = 'TOGGLE_FOLLOWING_PROGRESS';

export {
  FOLLOW,
  UNFOLLOW,
  ADD_POST,
  SET_USERS,
  SET_STATUS,
  DELETE_POST,
  SEND_MESSAGE,
  SET_USER_DATA,
  SET_INITIALIZED,
  SET_USER_PROFILE,
  SET_CURRENT_PAGE,
  SAVE_PHOTO_SUCCESS,
  TOGGLE_IS_FETCHING,
  SET_TOTAL_USERS_COUNT,
  SET_CAPTCHA_URL_SUCCESS,
  UPDATE_NEW_MESSAGE_BODY,
  TOGGLE_FOLLOWING_PROGRESS,
};
