const ADD_POST = 'ADD-POST';
const UPDATE_NEW_MESSAGE_BODY = 'UPDATE-NEW-MESSAGE-BODY';
const SEND_MESSAGE = 'SEND-MESSAGE';
const FOLLOW = 'FOLLOW';
const UNFOLLOW = 'UNFOLLOW';
const SET_USERS = 'SET_USERS';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
const TOGGLE_FOLLOWING_PROGRESS = 'TOGGLE_FOLLOWING_PROGRESS';
const SET_USER_PROFILE = 'SET_USER_PROFILE';
const SET_USER_DATA = 'SET_USER_DATA';
const SET_STATUS = 'SET_STATUS';
const SET_INITIALIZED = 'SET_INITIALIZED';


export {
  FOLLOW,
  UNFOLLOW,
  ADD_POST,
  SET_USERS,
  SET_STATUS,
  SEND_MESSAGE,
  SET_USER_DATA,
  SET_INITIALIZED,
  SET_USER_PROFILE,
  SET_CURRENT_PAGE,
  TOGGLE_IS_FETCHING,
  SET_TOTAL_USERS_COUNT,
  UPDATE_NEW_MESSAGE_BODY,
  TOGGLE_FOLLOWING_PROGRESS,
};
