const ADD_POST = 'ADD-POST';
const UPDATE_NEW_POST_TEXT = 'UPDATE-NEW-POST-TEXT';
const UPDATE_NEW_MESSAGE_BODY = 'UPDATE-NEW-MESSAGE-BODY';
const SEND_MESSAGE = 'SEND-MESSAGE';

export {
    ADD_POST,
    UPDATE_NEW_POST_TEXT,
    UPDATE_NEW_MESSAGE_BODY,
    SEND_MESSAGE
};
