const DEFAULT_LIKES_VALUE = 0;
const NEXT_ID = 8;
const DEFAULT_USER_ID = 2;
const API_KEY = 'a330ffbb-7ace-4dc9-a8ec-7880ecab78ff';
const ALT_PROFILE_AVATAR = 'Avatar';
const ALT_USER_AVATAR = 'User Avatar';
const WELL = 0;

export {
  DEFAULT_LIKES_VALUE, NEXT_ID, DEFAULT_USER_ID, API_KEY, ALT_PROFILE_AVATAR, ALT_USER_AVATAR, WELL,
};
